# Generated by Django 4.2.3 on 2023-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vinos_blancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vinos_espumantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vinos_rosados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vinos_tintos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
    ]
