# Generated by Django 4.2.3 on 2023-08-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vino_blanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vino_espumante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vino_rosado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vino_tinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=50)),
                ('cosecha', models.DateField()),
            ],
        ),
    ]
